
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: managedclusterprofilebindings.profile.k8s.appscode.com
spec:
  group: profile.k8s.appscode.com
  names:
    kind: ManagedClusterProfileBinding
    listKind: ManagedClusterProfileBindingList
    plural: managedclusterprofilebindings
    singular: managedclusterprofilebinding
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              clusterMetadata:
                properties:
                  capi:
                    properties:
                      clusterName:
                        type: string
                      namespace:
                        type: string
                      provider:
                        enum:
                        - capa
                        - capg
                        - capz
                        type: string
                    type: object
                  clusterManagers:
                    items:
                      type: string
                    type: array
                  name:
                    type: string
                  uid:
                    type: string
                required:
                - clusterManagers
                - name
                - uid
                type: object
              profileRef:
                properties:
                  name:
                    default: ""
                    type: string
                type: object
                x-kubernetes-map-type: atomic
            required:
            - clusterMetadata
            - profileRef
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    reason:
                      type: string
                    severity:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - status
                  - type
                  type: object
                type: array
              manifestWorks:
                additionalProperties:
                  type: string
                type: object
              observedGeneration:
                format: int64
                type: integer
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
